#!/bin/bash
echo "🔍 Google Analytics Verification Script"
echo "======================================"
echo "Your ID: 505841822"
echo "Likely Measurement ID: G-505841822"
echo ""

echo "📋 Verification Steps:"
echo "1. Visit https://marketplace-pro.github.io/"
echo "2. Open Google Analytics → Realtime report"
echo "3. Wait 1-2 minutes"
echo "4. You should see 1 active user (yourself)"
echo ""
echo "🔧 If not working, try these alternatives:"
echo "• Property ID only: 505841822"
echo "• Universal Analytics: UA-505841822-1"
echo "• Check GA admin for exact Measurement ID"
echo ""
echo "💡 Your GA4 property might use:"
echo "• G-505841822 (most likely)"
echo "• Or check Properties → Data Streams → Web → Measurement ID"
